# Generated by Django 3.0.5 on 2020-04-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
